language: python
python: "2.7"
# command to install dependencies
#install:
  #- pip install -q -e . --use-mirrors
  #- pip install scapy
#install: "pip install -r requirements.txt"
# command to run tests
script:
  - python build.py install

notifications:
  slack: daleslab:iOjNthhpWvGcIYlDK532APwS
